// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"

	"github.com/xRiErOS/beans/pkg/bean"
)

// Lightweight status for tracking which beans have running agents
type ActiveAgentStatus struct {
	// Bean ID with an active agent
	BeanID string `json:"beanId"`
	// Current agent status
	Status AgentSessionStatus `json:"status"`
}

// An action that can be performed by the agent
type AgentAction struct {
	// Unique identifier for the action
	ID string `json:"id"`
	// Human-readable label
	Label string `json:"label"`
	// Description of what the action does
	Description *string `json:"description,omitempty"`
	// Whether the action is currently disabled
	Disabled bool `json:"disabled"`
	// Reason why the action is disabled (shown as tooltip)
	DisabledReason *string `json:"disabledReason,omitempty"`
}

// A single message in an agent conversation
type AgentMessage struct {
	// Message role
	Role AgentMessageRole `json:"role"`
	// Text content
	Content string `json:"content"`
	// Attached images (empty for assistant/tool messages)
	Images []*AgentMessageImage `json:"images"`
	// File/directory paths attached via @-mention (only present on user messages)
	Attachments []string `json:"attachments"`
	// Unified diff output (only present on tool messages for Write/Edit tools)
	Diff *string `json:"diff,omitempty"`
}

// An image attached to an agent message
type AgentMessageImage struct {
	// URL to fetch the image
	URL string `json:"url"`
	// MIME type (e.g. image/png)
	MediaType string `json:"mediaType"`
}

// An agent chat session within a worktree
type AgentSession struct {
	// Bean ID (worktree identifier)
	BeanID string `json:"beanId"`
	// Agent type (e.g., 'claude')
	AgentType string `json:"agentType"`
	// Current session status
	Status AgentSessionStatus `json:"status"`
	// Chat messages in chronological order
	Messages []*AgentMessage `json:"messages"`
	// Last error message, if any
	Error *string `json:"error,omitempty"`
	// Thinking effort level (e.g. 'low', 'medium', 'high', 'max'), null when using CLI default
	Effort *string `json:"effort,omitempty"`
	// Whether the agent is in plan mode (read-only)
	PlanMode bool `json:"planMode"`
	// Whether the agent is in act mode (fully autonomous, no permission prompts)
	ActMode bool `json:"actMode"`
	// Transient system status (e.g. 'compacting'), null when idle
	SystemStatus *string `json:"systemStatus,omitempty"`
	// Pending blocking interaction awaiting user response
	PendingInteraction *PendingInteraction `json:"pendingInteraction,omitempty"`
	// Working directory / worktree path for this session
	WorkDir *string `json:"workDir,omitempty"`
	// Currently running subagent activities (one per concurrent Agent tool call)
	SubagentActivities []*SubagentActivity `json:"subagentActivities"`
	// Suggested quick reply messages generated after a turn completes
	QuickReplies []string `json:"quickReplies"`
}

// A selectable option within an AskUserQuestion
type AskUserOption struct {
	// Display text for this option
	Label string `json:"label"`
	// Explanation of what this option means
	Description string `json:"description"`
}

// A structured question with selectable options from the AskUserQuestion tool
type AskUserQuestion struct {
	// Short label displayed as a chip/tag
	Header string `json:"header"`
	// The full question text
	Question string `json:"question"`
	// Whether multiple options can be selected
	MultiSelect bool `json:"multiSelect"`
	// Available choices
	Options []*AskUserOption `json:"options"`
}

// Represents a change to a bean
type BeanChangeEvent struct {
	// Type of change that occurred
	Type ChangeType `json:"type"`
	// The bean that changed (null for INITIAL_SNAPSHOT and DELETED events)
	Bean *bean.Bean `json:"bean,omitempty"`
	// All beans as a batch (only present for INITIAL_SNAPSHOT events)
	Beans []*bean.Bean `json:"beans,omitempty"`
	// ID of the bean that changed (empty for INITIAL_SNAPSHOT events)
	BeanID string `json:"beanId"`
}

// Filter options for querying beans
type BeanFilter struct {
	// Full-text search across slug, title, and body using Bleve query syntax.
	//
	// Examples:
	// - "login" - exact term match
	// - "login~" - fuzzy match (1 edit distance)
	// - "login~2" - fuzzy match (2 edit distance)
	// - "log*" - wildcard prefix
	// - "\"user login\"" - exact phrase
	// - "user AND login" - both terms required
	// - "user OR login" - either term
	// - "slug:auth" - search only slug field
	// - "title:login" - search only title field
	// - "body:auth" - search only body field
	Search *string `json:"search,omitempty"`
	// Include only beans with these statuses (OR logic)
	Status []string `json:"status,omitempty"`
	// Exclude beans with these statuses
	ExcludeStatus []string `json:"excludeStatus,omitempty"`
	// Include only beans with these types (OR logic)
	Type []string `json:"type,omitempty"`
	// Exclude beans with these types
	ExcludeType []string `json:"excludeType,omitempty"`
	// Include only beans with these priorities (OR logic)
	Priority []string `json:"priority,omitempty"`
	// Exclude beans with these priorities
	ExcludePriority []string `json:"excludePriority,omitempty"`
	// Include only beans with any of these tags (OR logic)
	Tags []string `json:"tags,omitempty"`
	// Exclude beans with any of these tags
	ExcludeTags []string `json:"excludeTags,omitempty"`
	// Include only beans with a parent
	HasParent *bool `json:"hasParent,omitempty"`
	// Include only beans with this specific parent ID
	ParentID *string `json:"parentId,omitempty"`
	// Include only beans that are blocking other beans
	HasBlocking *bool `json:"hasBlocking,omitempty"`
	// Include only beans that are blocking this specific bean ID
	BlockingID *string `json:"blockingId,omitempty"`
	// Include beans that are blocked — explicitly (direct blockers) or implicitly (ancestor is blocked)
	IsBlocked *bool `json:"isBlocked,omitempty"`
	// Filter beans that are explicitly blocked (have direct active blockers)
	IsExplicitlyBlocked *bool `json:"isExplicitlyBlocked,omitempty"`
	// Filter beans that are implicitly blocked (an ancestor in the parent chain is blocked)
	IsImplicitlyBlocked *bool `json:"isImplicitlyBlocked,omitempty"`
	// Include only beans that have explicit blocked-by entries
	HasBlockedBy *bool `json:"hasBlockedBy,omitempty"`
	// Include only beans blocked by this specific bean ID (via blocked_by field)
	BlockedByID *string `json:"blockedById,omitempty"`
	// Exclude beans that have a parent
	NoParent *bool `json:"noParent,omitempty"`
	// Exclude beans that are blocking other beans
	NoBlocking *bool `json:"noBlocking,omitempty"`
	// Exclude beans that have explicit blocked-by entries
	NoBlockedBy *bool `json:"noBlockedBy,omitempty"`
	// Exclude beans that inherit a terminal status (scrapped or completed) from an ancestor
	ExcludeImplicitTerminal *bool `json:"excludeImplicitTerminal,omitempty"`
}

// Structured body modifications applied atomically.
// Operations are applied in order: all replacements sequentially, then append.
// If any operation fails, the entire mutation fails (transactional).
type BodyModification struct {
	// Text replacements applied sequentially in array order.
	// Each old text must match exactly once at the time it's applied.
	Replace []*ReplaceOperation `json:"replace,omitempty"`
	// Text to append after all replacements.
	// Appended with blank line separator.
	Append *string `json:"append,omitempty"`
}

// Branch status relative to the base branch
type BranchStatus struct {
	// Number of commits on the base branch not reachable from this branch
	CommitsBehind int `json:"commitsBehind"`
	// Whether rebasing onto the base branch would produce merge conflicts
	HasConflicts bool `json:"hasConflicts"`
}

// Input for creating a new bean
type CreateBeanInput struct {
	// Bean title (required)
	Title string `json:"title"`
	// Bean type (defaults to 'task')
	Type *string `json:"type,omitempty"`
	// Status (defaults to 'todo')
	Status *string `json:"status,omitempty"`
	// Priority level (defaults to 'normal')
	Priority *string `json:"priority,omitempty"`
	// Tags for categorization
	Tags []string `json:"tags,omitempty"`
	// Markdown body content
	Body *string `json:"body,omitempty"`
	// Parent bean ID (validated against type hierarchy)
	Parent *string `json:"parent,omitempty"`
	// Bean IDs this bean is blocking
	Blocking []string `json:"blocking,omitempty"`
	// Bean IDs that are blocking this bean
	BlockedBy []string `json:"blockedBy,omitempty"`
	// Custom ID prefix (overrides config prefix for this bean)
	Prefix *string `json:"prefix,omitempty"`
}

// Input for attaching a file or directory as context to an agent message.
type FileAttachmentInput struct {
	// Relative file or directory path
	Path string `json:"path"`
}

// A changed file in a git working tree
type FileChange struct {
	// File path relative to the repo/worktree root
	Path string `json:"path"`
	// Change status: modified, added, deleted, untracked, renamed
	Status string `json:"status"`
	// Number of added lines
	Additions int `json:"additions"`
	// Number of deleted lines
	Deletions int `json:"deletions"`
	// Whether this change is staged
	Staged bool `json:"staged"`
}

// A file entry in the project, used for @-mention autocomplete.
type FileEntry struct {
	// Relative path from the workspace root
	Path string `json:"path"`
}

// Input for uploading an image attachment
type ImageInput struct {
	// Base64-encoded image data
	Data string `json:"data"`
	// MIME type (image/jpeg, image/png, image/gif, image/webp)
	MediaType string `json:"mediaType"`
}

type Mutation struct {
}

// A blocking interaction the agent is waiting for user approval on
type PendingInteraction struct {
	// Type of interaction
	Type InteractionType `json:"type"`
	// Plan file content (for EXIT_PLAN only)
	PlanContent *string `json:"planContent,omitempty"`
	// Structured questions with selectable options (for ASK_USER only)
	Questions []*AskUserQuestion `json:"questions,omitempty"`
}

// A pull/merge request on a git forge (GitHub, GitLab, etc.)
type PullRequest struct {
	// PR number on the forge
	Number int `json:"number"`
	// PR title
	Title string `json:"title"`
	// Current state: open, closed, merged
	State string `json:"state"`
	// Web URL to view the PR
	URL string `json:"url"`
	// Whether this PR is a draft
	IsDraft bool `json:"isDraft"`
	// Aggregate CI check status: pass, fail, pending
	CheckStatus string `json:"checkStatus"`
	// Whether review requirements are met
	ReviewApproved bool `json:"reviewApproved"`
	// Whether the forge reports the PR can be merged
	Mergeable bool `json:"mergeable"`
}

type Query struct {
}

// A single text replacement operation.
type ReplaceOperation struct {
	// Text to find (must occur exactly once, cannot be empty)
	Old string `json:"old"`
	// Replacement text (can be empty to delete the matched text)
	New string `json:"new"`
}

// Tracks real-time activity of a running subagent (Agent tool invocation)
type SubagentActivity struct {
	// Unique task identifier for this subagent
	TaskID string `json:"taskId"`
	// Sequential index (1-based) for display
	Index int `json:"index"`
	// What the subagent is currently doing
	Description string `json:"description"`
	// Tool currently being used by the subagent (empty string when idle)
	CurrentTool string `json:"currentTool"`
}

type Subscription struct {
}

// Input for updating an existing bean
type UpdateBeanInput struct {
	// New title
	Title *string `json:"title,omitempty"`
	// New status
	Status *string `json:"status,omitempty"`
	// New type
	Type *string `json:"type,omitempty"`
	// New priority
	Priority *string `json:"priority,omitempty"`
	// Replace all tags (nil preserves existing, mutually exclusive with addTags/removeTags)
	Tags []string `json:"tags,omitempty"`
	// Add tags to existing list
	AddTags []string `json:"addTags,omitempty"`
	// Remove tags from existing list
	RemoveTags []string `json:"removeTags,omitempty"`
	// New body content (full replacement, mutually exclusive with bodyMod)
	Body *string `json:"body,omitempty"`
	// Structured body modifications (mutually exclusive with body)
	BodyMod *BodyModification `json:"bodyMod,omitempty"`
	// Set parent bean ID (null/empty to clear, validates type hierarchy)
	Parent *string `json:"parent,omitempty"`
	// Add beans to blocking list (validates cycles and existence)
	AddBlocking []string `json:"addBlocking,omitempty"`
	// Remove beans from blocking list
	RemoveBlocking []string `json:"removeBlocking,omitempty"`
	// Add beans to blocked-by list (validates cycles and existence)
	AddBlockedBy []string `json:"addBlockedBy,omitempty"`
	// Remove beans from blocked-by list
	RemoveBlockedBy []string `json:"removeBlockedBy,omitempty"`
	// Fractional index for manual ordering (used by board drag-and-drop)
	Order *string `json:"order,omitempty"`
	// ETag for optimistic concurrency control (optional)
	IfMatch *string `json:"ifMatch,omitempty"`
}

// Git status for a workspace (main repo or worktree)
type WorkspaceStatus struct {
	// Workspace identifier (__central__ for main repo, worktree ID for worktrees)
	ID string `json:"id"`
	// Whether the workspace has uncommitted changes or untracked files
	HasChanges bool `json:"hasChanges"`
	// Whether the workspace has commits not yet merged into the base branch
	HasUnmergedCommits bool `json:"hasUnmergedCommits"`
}

// A git worktree, either associated with a bean or standalone
type Worktree struct {
	// Unique worktree identifier
	ID string `json:"id"`
	// Human-readable name
	Name *string `json:"name,omitempty"`
	// Auto-generated summary of what this workspace is doing
	Description *string `json:"description,omitempty"`
	// Git branch name
	Branch string `json:"branch"`
	// Filesystem path to the worktree
	Path string `json:"path"`
	// Beans detected from changes in this worktree vs the base branch
	Beans []*bean.Bean `json:"beans"`
	// Whether the worktree has uncommitted changes or untracked files
	HasChanges bool `json:"hasChanges"`
	// Whether the worktree has commits not yet merged into the base branch
	HasUnmergedCommits bool `json:"hasUnmergedCommits"`
	// Number of commits on the base branch that are not in this worktree branch
	CommitsBehind int `json:"commitsBehind"`
	// Whether rebasing onto the base branch would produce merge conflicts
	HasConflicts bool `json:"hasConflicts"`
	// Post-creation setup status (null if no setup configured)
	SetupStatus *WorktreeSetupStatus `json:"setupStatus,omitempty"`
	// Error message if setup failed
	SetupError *string `json:"setupError,omitempty"`
	// Open pull/merge request for this worktree's branch (null if none)
	PullRequest *PullRequest `json:"pullRequest,omitempty"`
}

// Role of an agent message sender
type AgentMessageRole string

const (
	AgentMessageRoleUser      AgentMessageRole = "USER"
	AgentMessageRoleAssistant AgentMessageRole = "ASSISTANT"
	AgentMessageRoleTool      AgentMessageRole = "TOOL"
	AgentMessageRoleInfo      AgentMessageRole = "INFO"
)

var AllAgentMessageRole = []AgentMessageRole{
	AgentMessageRoleUser,
	AgentMessageRoleAssistant,
	AgentMessageRoleTool,
	AgentMessageRoleInfo,
}

func (e AgentMessageRole) IsValid() bool {
	switch e {
	case AgentMessageRoleUser, AgentMessageRoleAssistant, AgentMessageRoleTool, AgentMessageRoleInfo:
		return true
	}
	return false
}

func (e AgentMessageRole) String() string {
	return string(e)
}

func (e *AgentMessageRole) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = AgentMessageRole(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid AgentMessageRole", str)
	}
	return nil
}

func (e AgentMessageRole) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *AgentMessageRole) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e AgentMessageRole) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

// Status of an agent session
type AgentSessionStatus string

const (
	AgentSessionStatusIdle    AgentSessionStatus = "IDLE"
	AgentSessionStatusRunning AgentSessionStatus = "RUNNING"
	AgentSessionStatusError   AgentSessionStatus = "ERROR"
)

var AllAgentSessionStatus = []AgentSessionStatus{
	AgentSessionStatusIdle,
	AgentSessionStatusRunning,
	AgentSessionStatusError,
}

func (e AgentSessionStatus) IsValid() bool {
	switch e {
	case AgentSessionStatusIdle, AgentSessionStatusRunning, AgentSessionStatusError:
		return true
	}
	return false
}

func (e AgentSessionStatus) String() string {
	return string(e)
}

func (e *AgentSessionStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = AgentSessionStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid AgentSessionStatus", str)
	}
	return nil
}

func (e AgentSessionStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *AgentSessionStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e AgentSessionStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

// Type of change that occurred to a bean
type ChangeType string

const (
	// All existing beans sent as a single batch when subscription starts (emitted when includeInitial=true)
	ChangeTypeInitialSnapshot ChangeType = "INITIAL_SNAPSHOT"
	ChangeTypeCreated         ChangeType = "CREATED"
	ChangeTypeUpdated         ChangeType = "UPDATED"
	ChangeTypeDeleted         ChangeType = "DELETED"
)

var AllChangeType = []ChangeType{
	ChangeTypeInitialSnapshot,
	ChangeTypeCreated,
	ChangeTypeUpdated,
	ChangeTypeDeleted,
}

func (e ChangeType) IsValid() bool {
	switch e {
	case ChangeTypeInitialSnapshot, ChangeTypeCreated, ChangeTypeUpdated, ChangeTypeDeleted:
		return true
	}
	return false
}

func (e ChangeType) String() string {
	return string(e)
}

func (e *ChangeType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ChangeType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ChangeType", str)
	}
	return nil
}

func (e ChangeType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ChangeType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ChangeType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

// Type of blocking interaction
type InteractionType string

const (
	InteractionTypeExitPlan  InteractionType = "EXIT_PLAN"
	InteractionTypeEnterPlan InteractionType = "ENTER_PLAN"
	InteractionTypeAskUser   InteractionType = "ASK_USER"
)

var AllInteractionType = []InteractionType{
	InteractionTypeExitPlan,
	InteractionTypeEnterPlan,
	InteractionTypeAskUser,
}

func (e InteractionType) IsValid() bool {
	switch e {
	case InteractionTypeExitPlan, InteractionTypeEnterPlan, InteractionTypeAskUser:
		return true
	}
	return false
}

func (e InteractionType) String() string {
	return string(e)
}

func (e *InteractionType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = InteractionType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid InteractionType", str)
	}
	return nil
}

func (e InteractionType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *InteractionType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e InteractionType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

// Status of a worktree's post-creation setup command
type WorktreeSetupStatus string

const (
	WorktreeSetupStatusRunning WorktreeSetupStatus = "RUNNING"
	WorktreeSetupStatusDone    WorktreeSetupStatus = "DONE"
	WorktreeSetupStatusFailed  WorktreeSetupStatus = "FAILED"
)

var AllWorktreeSetupStatus = []WorktreeSetupStatus{
	WorktreeSetupStatusRunning,
	WorktreeSetupStatusDone,
	WorktreeSetupStatusFailed,
}

func (e WorktreeSetupStatus) IsValid() bool {
	switch e {
	case WorktreeSetupStatusRunning, WorktreeSetupStatusDone, WorktreeSetupStatusFailed:
		return true
	}
	return false
}

func (e WorktreeSetupStatus) String() string {
	return string(e)
}

func (e *WorktreeSetupStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = WorktreeSetupStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid WorktreeSetupStatus", str)
	}
	return nil
}

func (e WorktreeSetupStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *WorktreeSetupStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e WorktreeSetupStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
