package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.84

import (
	"context"
	"encoding/base64"
	"fmt"
	"log"
	"os/exec"
	"path/filepath"
	"strings"
	"sync"
	"time"

	"github.com/xRiErOS/beans/internal/agent"
	"github.com/xRiErOS/beans/internal/gitutil"
	"github.com/xRiErOS/beans/internal/worktree"
	"github.com/xRiErOS/beans/pkg/bean"
	"github.com/xRiErOS/beans/pkg/beancore"
	"github.com/xRiErOS/beans/pkg/beangraph/model"
	"github.com/xRiErOS/beans/pkg/config"
)

// IsDirty is the resolver for the isDirty field.
func (r *beanResolver) IsDirty(ctx context.Context, obj *bean.Bean) (bool, error) {
	return r.CoreResolver.BeanIsDirty(ctx, obj)
}

// WorktreeID is the resolver for the worktreeId field.
func (r *beanResolver) WorktreeID(ctx context.Context, obj *bean.Bean) (*string, error) {
	return r.CoreResolver.BeanWorktreeID(ctx, obj)
}

// ParentID is the resolver for the parentId field.
func (r *beanResolver) ParentID(ctx context.Context, obj *bean.Bean) (*string, error) {
	return r.CoreResolver.BeanParentID(ctx, obj)
}

// BlockingIds is the resolver for the blockingIds field.
func (r *beanResolver) BlockingIds(ctx context.Context, obj *bean.Bean) ([]string, error) {
	return r.CoreResolver.BeanBlockingIds(ctx, obj)
}

// BlockedByIds is the resolver for the blockedByIds field.
func (r *beanResolver) BlockedByIds(ctx context.Context, obj *bean.Bean) ([]string, error) {
	return r.CoreResolver.BeanBlockedByIds(ctx, obj)
}

// BlockedBy is the resolver for the blockedBy field.
func (r *beanResolver) BlockedBy(ctx context.Context, obj *bean.Bean, filter *model.BeanFilter) ([]*bean.Bean, error) {
	return r.CoreResolver.BeanBlockedBy(ctx, obj, filter)
}

// Blocking is the resolver for the blocking field.
func (r *beanResolver) Blocking(ctx context.Context, obj *bean.Bean, filter *model.BeanFilter) ([]*bean.Bean, error) {
	return r.CoreResolver.BeanBlocking(ctx, obj, filter)
}

// Parent is the resolver for the parent field.
func (r *beanResolver) Parent(ctx context.Context, obj *bean.Bean) (*bean.Bean, error) {
	return r.CoreResolver.BeanParent(ctx, obj)
}

// Children is the resolver for the children field.
func (r *beanResolver) Children(ctx context.Context, obj *bean.Bean, filter *model.BeanFilter) ([]*bean.Bean, error) {
	return r.CoreResolver.BeanChildren(ctx, obj, filter)
}

// ImplicitStatus is the resolver for the implicitStatus field.
func (r *beanResolver) ImplicitStatus(ctx context.Context, obj *bean.Bean) (*string, error) {
	return r.CoreResolver.BeanImplicitStatus(ctx, obj)
}

// ImplicitStatusFrom is the resolver for the implicitStatusFrom field.
func (r *beanResolver) ImplicitStatusFrom(ctx context.Context, obj *bean.Bean) (*string, error) {
	return r.CoreResolver.BeanImplicitStatusFrom(ctx, obj)
}

// CreateBean is the resolver for the createBean field.
func (r *mutationResolver) CreateBean(ctx context.Context, input model.CreateBeanInput) (*bean.Bean, error) {
	return r.CoreResolver.CreateBean(ctx, input)
}

// UpdateBean is the resolver for the updateBean field.
func (r *mutationResolver) UpdateBean(ctx context.Context, id string, input model.UpdateBeanInput) (*bean.Bean, error) {
	return r.CoreResolver.UpdateBean(ctx, id, input)
}

// DeleteBean is the resolver for the deleteBean field.
func (r *mutationResolver) DeleteBean(ctx context.Context, id string) (bool, error) {
	return r.CoreResolver.DeleteBean(ctx, id)
}

// SetParent is the resolver for the setParent field.
func (r *mutationResolver) SetParent(ctx context.Context, id string, parentID *string, ifMatch *string) (*bean.Bean, error) {
	return r.CoreResolver.SetParent(ctx, id, parentID, ifMatch)
}

// AddBlocking is the resolver for the addBlocking field.
func (r *mutationResolver) AddBlocking(ctx context.Context, id string, targetID string, ifMatch *string) (*bean.Bean, error) {
	return r.CoreResolver.AddBlocking(ctx, id, targetID, ifMatch)
}

// RemoveBlocking is the resolver for the removeBlocking field.
func (r *mutationResolver) RemoveBlocking(ctx context.Context, id string, targetID string, ifMatch *string) (*bean.Bean, error) {
	return r.CoreResolver.RemoveBlocking(ctx, id, targetID, ifMatch)
}

// AddBlockedBy is the resolver for the addBlockedBy field.
func (r *mutationResolver) AddBlockedBy(ctx context.Context, id string, targetID string, ifMatch *string) (*bean.Bean, error) {
	return r.CoreResolver.AddBlockedBy(ctx, id, targetID, ifMatch)
}

// RemoveBlockedBy is the resolver for the removeBlockedBy field.
func (r *mutationResolver) RemoveBlockedBy(ctx context.Context, id string, targetID string, ifMatch *string) (*bean.Bean, error) {
	return r.CoreResolver.RemoveBlockedBy(ctx, id, targetID, ifMatch)
}

// WriteTerminalInput is the resolver for the writeTerminalInput field.
// Creates the session on demand if it doesn't exist yet.
func (r *mutationResolver) WriteTerminalInput(ctx context.Context, sessionID string, data string) (bool, error) {
	if r.TerminalMgr == nil {
		return false, fmt.Errorf("terminal support not available")
	}

	sess := r.TerminalMgr.Get(sessionID)
	if sess == nil {
		// Session doesn't exist yet — create it on demand so callers
		// don't need to race against the terminal pane's WebSocket init.
		var workDir string
		if sessionID == CentralSessionID {
			workDir = r.ProjectRoot
		} else if r.WorktreeMgr != nil {
			workDir = r.WorktreeMgr.WorktreePath(sessionID)
		}
		if workDir == "" {
			return false, fmt.Errorf("terminal session %q not found and cannot resolve work dir", sessionID)
		}
		var err error
		sess, _, err = r.TerminalMgr.GetOrCreate(sessionID, workDir, 80, 24)
		if err != nil {
			return false, fmt.Errorf("failed to create terminal session: %w", err)
		}
	}

	if _, err := sess.Write([]byte(data)); err != nil {
		return false, fmt.Errorf("write to terminal: %w", err)
	}

	return true, nil
}

// StartRun is the resolver for the startRun field.
func (r *mutationResolver) StartRun(ctx context.Context, workspaceID string) (int, error) {
	if r.TerminalMgr == nil {
		return 0, fmt.Errorf("terminal support not available")
	}

	cfg := r.Core.Config()
	if cfg == nil || cfg.GetWorktreeRun() == "" {
		return 0, fmt.Errorf("no run command configured")
	}

	var workDir string
	if workspaceID == CentralSessionID {
		workDir = r.ProjectRoot
	} else if r.WorktreeMgr != nil {
		workDir = r.WorktreeMgr.WorktreePath(workspaceID)
	}
	if workDir == "" {
		return 0, fmt.Errorf("cannot resolve work directory for workspace %q", workspaceID)
	}

	sessionID := workspaceID + RunSessionSuffix
	if _, err := r.TerminalMgr.CreateWithCommand(sessionID, workDir, 80, 24, cfg.GetWorktreeRun()); err != nil {
		return 0, fmt.Errorf("failed to start run session: %w", err)
	}

	port := 0
	if r.PortAlloc != nil {
		if p, err := r.PortAlloc.Get(workspaceID); err == nil {
			port = p
		}
	}

	return port, nil
}

// StopRun is the resolver for the stopRun field.
func (r *mutationResolver) StopRun(ctx context.Context, workspaceID string) (bool, error) {
	if r.TerminalMgr == nil {
		return false, fmt.Errorf("terminal support not available")
	}

	sessionID := workspaceID + RunSessionSuffix
	r.TerminalMgr.Close(sessionID)
	return true, nil
}

// CreateWorktree is the resolver for the createWorktree field.
func (r *mutationResolver) CreateWorktree(ctx context.Context, name string) (*model.Worktree, error) {
	if r.WorktreeMgr == nil {
		return nil, fmt.Errorf("worktree support not available")
	}

	wt, err := r.WorktreeMgr.Create(name)
	if err != nil {
		return nil, err
	}

	// Allocate a workspace port for this worktree and persist it
	if r.PortAlloc != nil {
		port := r.PortAlloc.Allocate(wt.ID)
		if err := r.WorktreeMgr.SavePort(wt.ID, port); err != nil {
			log.Printf("[worktree] warning: failed to save port for %s: %v", wt.ID, err)
		}
	}

	// Start watching the worktree's .beans/ directory for bean changes
	if err := r.Core.WatchWorktreeBeans(wt.Path); err != nil {
		fmt.Printf("[beans] warning: failed to watch worktree beans: %v\n", err)
	}

	return worktreeToModel(wt, r.Core, r.WorktreeMgr.BaseRef(), false), nil
}

// RemoveWorktree is the resolver for the removeWorktree field.
func (r *mutationResolver) RemoveWorktree(ctx context.Context, id string) (bool, error) {
	if r.WorktreeMgr == nil {
		return false, fmt.Errorf("worktree support not available")
	}

	// Find the worktree path before removing (for unwatching)
	worktrees, _ := r.WorktreeMgr.List()
	for _, wt := range worktrees {
		if wt.ID == id {
			r.Core.UnwatchWorktreeBeans(wt.Path)
			break
		}
	}

	if err := r.WorktreeMgr.Remove(id); err != nil {
		return false, err
	}

	// Free the workspace port
	if r.PortAlloc != nil {
		r.PortAlloc.Free(id)
	}

	// Close any terminal session associated with this worktree
	if r.TerminalMgr != nil {
		r.TerminalMgr.Close(id)
	}

	return true, nil
}

// SendAgentMessage is the resolver for the sendAgentMessage field.
func (r *mutationResolver) SendAgentMessage(ctx context.Context, beanID string, message string, images []*model.ImageInput, attachments []*model.FileAttachmentInput) (bool, error) {
	if r.AgentMgr == nil {
		return false, fmt.Errorf("agent manager not available")
	}

	var workDir string
	if beanID == CentralSessionID {
		// Central agent chat runs in the project root
		workDir = r.ProjectRoot
	} else {
		// Find the worktree path for this bean
		var err error
		workDir, err = r.findWorktreePath(beanID)
		if err != nil {
			return false, err
		}
	}

	var attachmentPaths []string
	for _, a := range attachments {
		attachmentPaths = append(attachmentPaths, a.Path)
	}

	var uploads []agent.ImageUpload
	for _, img := range images {
		data, err := base64.StdEncoding.DecodeString(img.Data)
		if err != nil {
			return false, fmt.Errorf("invalid base64 image data: %w", err)
		}
		uploads = append(uploads, agent.ImageUpload{Data: data, MediaType: img.MediaType})
	}

	if err := r.AgentMgr.SendMessage(beanID, workDir, message, uploads, attachmentPaths...); err != nil {
		return false, err
	}
	return true, nil
}

// StopAgent is the resolver for the stopAgent field.
func (r *mutationResolver) StopAgent(ctx context.Context, beanID string) (bool, error) {
	if r.AgentMgr == nil {
		return false, fmt.Errorf("agent manager not available")
	}
	if err := r.AgentMgr.StopSession(beanID); err != nil {
		return false, err
	}
	return true, nil
}

// SetAgentPlanMode is the resolver for the setAgentPlanMode field.
func (r *mutationResolver) SetAgentPlanMode(ctx context.Context, beanID string, planMode bool) (bool, error) {
	if r.AgentMgr == nil {
		return false, fmt.Errorf("agent manager not available")
	}
	if err := r.AgentMgr.SetPlanMode(beanID, planMode); err != nil {
		return false, err
	}
	return true, nil
}

// SetAgentActMode is the resolver for the setAgentActMode field.
func (r *mutationResolver) SetAgentActMode(ctx context.Context, beanID string, actMode bool) (bool, error) {
	if r.AgentMgr == nil {
		return false, fmt.Errorf("agent manager not available")
	}
	if err := r.AgentMgr.SetActMode(beanID, actMode); err != nil {
		return false, err
	}
	return true, nil
}

// SetAgentEffort is the resolver for the setAgentEffort field.
func (r *mutationResolver) SetAgentEffort(ctx context.Context, beanID string, effort string) (bool, error) {
	if r.AgentMgr == nil {
		return false, fmt.Errorf("agent manager not available")
	}
	if err := r.AgentMgr.SetEffort(beanID, effort); err != nil {
		return false, err
	}
	return true, nil
}

// SetAgentPendingInteraction is the resolver for the setAgentPendingInteraction field.
func (r *mutationResolver) SetAgentPendingInteraction(ctx context.Context, beanID string, typeArg model.InteractionType, planContent *string) (bool, error) {
	if r.AgentMgr == nil {
		return false, fmt.Errorf("agent manager not available")
	}
	var itype agent.InteractionType
	switch typeArg {
	case model.InteractionTypeExitPlan:
		itype = agent.InteractionExitPlan
	case model.InteractionTypeEnterPlan:
		itype = agent.InteractionEnterPlan
	case model.InteractionTypeAskUser:
		itype = agent.InteractionAskUser
	}
	interaction := &agent.PendingInteraction{Type: itype}
	if planContent != nil {
		interaction.PlanContent = *planContent
	}
	if err := r.AgentMgr.SetPendingInteraction(beanID, interaction); err != nil {
		return false, err
	}
	return true, nil
}

// ClearAgentSession is the resolver for the clearAgentSession field.
func (r *mutationResolver) ClearAgentSession(ctx context.Context, beanID string) (bool, error) {
	if r.AgentMgr == nil {
		return false, fmt.Errorf("agent manager not available")
	}
	if err := r.AgentMgr.ClearSession(beanID); err != nil {
		return false, err
	}
	return true, nil
}

// ArchiveBean is the resolver for the archiveBean field.
func (r *mutationResolver) ArchiveBean(ctx context.Context, id string) (bool, error) {
	return r.CoreResolver.ArchiveBean(ctx, id)
}

// SaveDirtyBeans is the resolver for the saveDirtyBeans field.
func (r *mutationResolver) SaveDirtyBeans(ctx context.Context) (int, error) {
	return r.Core.SaveDirty()
}

// SaveBean is the resolver for the saveBean field.
func (r *mutationResolver) SaveBean(ctx context.Context, id string) (bool, error) {
	if err := r.Core.SaveBean(id); err != nil {
		return false, err
	}
	return true, nil
}

// ExecuteAgentAction is the resolver for the executeAgentAction field.
func (r *mutationResolver) ExecuteAgentAction(ctx context.Context, beanID string, actionID string) (bool, error) {
	if r.AgentMgr == nil {
		return false, fmt.Errorf("agent manager not available")
	}

	action := findAgentAction(actionID)
	if action == nil {
		return false, fmt.Errorf("unknown agent action: %s", actionID)
	}

	var workDir string
	if beanID == CentralSessionID {
		workDir = r.ProjectRoot
	} else {
		var err error
		workDir, err = r.findWorktreePath(beanID)
		if err != nil {
			return false, err
		}
	}

	actCtx := actionContext{WorktreeID: beanID, WorkDir: workDir, MainRepoPath: r.ProjectRoot}

	// Populate git state
	actCtx.HasChanges = gitutil.HasChanges(workDir)
	if r.WorktreeMgr != nil {
		actCtx.HasNewCommits = gitutil.HasUnmergedCommits(workDir, r.WorktreeMgr.BaseRef())
		actCtx.HasUnpushedCommits = gitutil.HasUnpushedCommits(workDir)
	}

	// Populate forge/PR state
	if r.Forge != nil {
		actCtx.ForgeCLI = r.Forge.CLIName()
		if branch, ok := gitutil.CurrentBranch(workDir); ok {
			pr, _ := r.Forge.FindPR(ctx, r.ProjectRoot, branch)
			actCtx.PullRequest = pr
		}
	}

	if err := r.AgentMgr.SendMessage(beanID, workDir, action.PromptFunc(actCtx), nil); err != nil {
		return false, err
	}
	return true, nil
}

// DiscardFileChange is the resolver for the discardFileChange field.
func (r *mutationResolver) DiscardFileChange(ctx context.Context, filePath string, staged bool, path *string) (bool, error) {
	dir := r.ProjectRoot
	if path != nil && *path != "" {
		if r.WorktreeMgr != nil {
			wts, err := r.WorktreeMgr.List()
			if err != nil {
				return false, err
			}
			valid := false
			for _, wt := range wts {
				if wt.Path == *path {
					valid = true
					break
				}
			}
			if !valid {
				return false, fmt.Errorf("unknown worktree path: %s", *path)
			}
		}
		dir = *path
	}

	if err := gitutil.DiscardFileChange(dir, filePath, staged); err != nil {
		return false, err
	}
	return true, nil
}

// OpenInEditor is the resolver for the openInEditor field.
func (r *mutationResolver) OpenInEditor(ctx context.Context, workspaceID string) (bool, error) {
	var dir string
	if workspaceID == CentralSessionID {
		dir = r.ProjectRoot
	} else {
		if r.WorktreeMgr == nil {
			return false, fmt.Errorf("worktree support not available")
		}
		wts, err := r.WorktreeMgr.List()
		if err != nil {
			return false, err
		}
		for _, wt := range wts {
			if wt.ID == workspaceID {
				dir = wt.Path
				break
			}
		}
		if dir == "" {
			return false, fmt.Errorf("worktree not found: %s", workspaceID)
		}
	}

	cmd := exec.Command("code", dir)
	if err := cmd.Start(); err != nil {
		return false, fmt.Errorf("failed to open editor: %w", err)
	}
	// Don't wait for the process — VS Code detaches itself
	go cmd.Wait()

	return true, nil
}

// Bean is the resolver for the bean field.
func (r *queryResolver) Bean(ctx context.Context, id string) (*bean.Bean, error) {
	return r.CoreResolver.Bean(ctx, id)
}

// Beans is the resolver for the beans field.
func (r *queryResolver) Beans(ctx context.Context, filter *model.BeanFilter) ([]*bean.Bean, error) {
	return r.CoreResolver.Beans(ctx, filter)
}

// Worktrees is the resolver for the worktrees field.
func (r *queryResolver) Worktrees(ctx context.Context) ([]*model.Worktree, error) {
	if r.WorktreeMgr == nil {
		return []*model.Worktree{}, nil
	}

	wts, err := r.WorktreeMgr.List()
	if err != nil {
		return nil, err
	}

	result := make([]*model.Worktree, len(wts))
	for i, wt := range wts {
		result[i] = worktreeToModel(&wt, r.Core, r.WorktreeMgr.BaseRef(), true)
	}
	populatePRsBatch(ctx, result, r.Forge, r.ProjectRoot)
	return result, nil
}

// AgentSession is the resolver for the agentSession field.
func (r *queryResolver) AgentSession(ctx context.Context, beanID string) (*model.AgentSession, error) {
	if r.AgentMgr == nil {
		return nil, nil
	}
	s := r.AgentMgr.GetSession(beanID)
	if s == nil {
		return nil, nil
	}
	return agentSessionToModel(s), nil
}

// FileChanges is the resolver for the fileChanges field.
func (r *queryResolver) FileChanges(ctx context.Context, path *string) ([]*model.FileChange, error) {
	dir := r.ProjectRoot
	if path != nil && *path != "" {
		// Validate the path is a known worktree to prevent arbitrary filesystem access
		if r.WorktreeMgr != nil {
			wts, err := r.WorktreeMgr.List()
			if err != nil {
				return nil, err
			}
			valid := false
			for _, wt := range wts {
				if wt.Path == *path {
					valid = true
					break
				}
			}
			if !valid {
				return nil, fmt.Errorf("unknown worktree path: %s", *path)
			}
		}
		dir = *path
	}

	changes, err := gitutil.FileChanges(dir)
	if err != nil {
		return nil, err
	}

	result := make([]*model.FileChange, len(changes))
	for i, c := range changes {
		result[i] = &model.FileChange{
			Path:      c.Path,
			Status:    c.Status,
			Additions: c.Additions,
			Deletions: c.Deletions,
			Staged:    c.Staged,
		}
	}
	return result, nil
}

// AllFileChanges is the resolver for the allFileChanges field.
func (r *queryResolver) AllFileChanges(ctx context.Context, path *string) ([]*model.FileChange, error) {
	dir := r.ProjectRoot
	if path != nil && *path != "" {
		if r.WorktreeMgr != nil {
			wts, err := r.WorktreeMgr.List()
			if err != nil {
				return nil, err
			}
			valid := false
			for _, wt := range wts {
				if wt.Path == *path {
					valid = true
					break
				}
			}
			if !valid {
				return nil, fmt.Errorf("unknown worktree path: %s", *path)
			}
		}
		dir = *path
	}

	var baseRef string
	if r.WorktreeMgr != nil {
		baseRef = r.WorktreeMgr.BaseRef()
	}
	changes, err := gitutil.AllChangesVsUpstream(dir, baseRef)
	if err != nil {
		return nil, err
	}

	result := make([]*model.FileChange, len(changes))
	for i, c := range changes {
		result[i] = &model.FileChange{
			Path:      c.Path,
			Status:    c.Status,
			Additions: c.Additions,
			Deletions: c.Deletions,
			Staged:    c.Staged,
		}
	}
	return result, nil
}

// FileDiff is the resolver for the fileDiff field.
func (r *queryResolver) FileDiff(ctx context.Context, filePath string, staged bool, path *string) (string, error) {
	// Sanitize filePath to prevent path traversal
	cleaned := filepath.Clean(filePath)
	if filepath.IsAbs(cleaned) || strings.HasPrefix(cleaned, "..") {
		return "", fmt.Errorf("invalid file path: %s", filePath)
	}

	dir := r.ProjectRoot
	if path != nil && *path != "" {
		// Validate the path is a known worktree to prevent arbitrary filesystem access
		if r.WorktreeMgr != nil {
			wts, err := r.WorktreeMgr.List()
			if err != nil {
				return "", err
			}
			valid := false
			for _, wt := range wts {
				if wt.Path == *path {
					valid = true
					break
				}
			}
			if !valid {
				return "", fmt.Errorf("unknown worktree path: %s", *path)
			}
		}
		dir = *path
	}

	return gitutil.FileDiff(dir, filePath, staged)
}

// AllFileDiff is the resolver for the allFileDiff field.
func (r *queryResolver) AllFileDiff(ctx context.Context, filePath string, path *string) (string, error) {
	cleaned := filepath.Clean(filePath)
	if filepath.IsAbs(cleaned) || strings.HasPrefix(cleaned, "..") {
		return "", fmt.Errorf("invalid file path: %s", filePath)
	}

	dir := r.ProjectRoot
	if path != nil && *path != "" {
		if r.WorktreeMgr != nil {
			wts, err := r.WorktreeMgr.List()
			if err != nil {
				return "", err
			}
			valid := false
			for _, wt := range wts {
				if wt.Path == *path {
					valid = true
					break
				}
			}
			if !valid {
				return "", fmt.Errorf("unknown worktree path: %s", *path)
			}
		}
		dir = *path
	}

	var baseRef string
	if r.WorktreeMgr != nil {
		baseRef = r.WorktreeMgr.BaseRef()
	}
	return gitutil.AllFileDiff(dir, filePath, baseRef)
}

// BranchStatus is the resolver for the branchStatus field.
func (r *queryResolver) BranchStatus(ctx context.Context, path *string) (*model.BranchStatus, error) {
	dir := r.ProjectRoot
	if path != nil && *path != "" {
		if r.WorktreeMgr != nil {
			wts, err := r.WorktreeMgr.List()
			if err != nil {
				return nil, err
			}
			valid := false
			for _, wt := range wts {
				if wt.Path == *path {
					valid = true
					break
				}
			}
			if !valid {
				return nil, fmt.Errorf("unknown worktree path: %s", *path)
			}
		}
		dir = *path
	}

	var baseRef string
	if r.WorktreeMgr != nil {
		baseRef = r.WorktreeMgr.BaseRef()
	}

	return &model.BranchStatus{
		CommitsBehind: gitutil.CommitsBehind(dir, baseRef),
		HasConflicts:  gitutil.HasConflicts(dir, baseRef),
	}, nil
}

// HasDirtyBeans is the resolver for the hasDirtyBeans field.
func (r *queryResolver) HasDirtyBeans(ctx context.Context) (bool, error) {
	return r.Core.HasDirty(), nil
}

// AgentActions is the resolver for the agentActions field.
func (r *queryResolver) AgentActions(ctx context.Context, beanID string, skipForge *bool) ([]*model.AgentAction, error) {
	// Build action context for visibility filtering
	actCtx := actionContext{WorktreeID: beanID}

	// Set integrate mode from config
	if cfg := r.Core.Config(); cfg != nil {
		actCtx.IntegrateMode = string(cfg.GetWorktreeIntegrate())
	} else {
		actCtx.IntegrateMode = string(config.IntegrateModeLocal)
	}

	// Check if this worktree exists and gather its state
	var branch string
	if r.WorktreeMgr != nil {
		actCtx.MainRepoHasChanges = gitutil.HasChanges(r.WorktreeMgr.RepoRoot())

		if wts, err := r.WorktreeMgr.List(); err == nil {
			for _, wt := range wts {
				if wt.ID == beanID {
					actCtx.WorkDir = wt.Path
					actCtx.HasChanges = gitutil.HasChanges(wt.Path)
					actCtx.HasNewCommits = gitutil.HasUnmergedCommits(wt.Path, r.WorktreeMgr.BaseRef())
					actCtx.HasUnpushedCommits = gitutil.HasUnpushedCommits(wt.Path)
					actCtx.HasConflicts = gitutil.HasConflicts(wt.Path, r.WorktreeMgr.BaseRef())
					branch = wt.Branch
					break
				}
			}
		}
	}

	// Populate forge context
	if r.Forge != nil {
		actCtx.ForgeCLI = r.Forge.CLIName()
		if skipForge != nil && *skipForge {
			// Show the PR button in loading state while the full fetch is pending
			actCtx.ForgeLoading = true
		} else if branch != "" {
			pr, _ := r.Forge.FindPR(ctx, r.ProjectRoot, branch)
			actCtx.PullRequest = pr
		}
	}

	var result []*model.AgentAction
	for _, a := range agentActions {
		if a.Visible != nil && !a.Visible(actCtx) {
			continue
		}
		label := a.Label
		if a.LabelFunc != nil {
			label = a.LabelFunc(actCtx)
		}
		desc := a.Description
		action := &model.AgentAction{
			ID:          a.ID,
			Label:       label,
			Description: &desc,
		}
		if a.Disabled != nil {
			if reason := a.Disabled(actCtx); reason != "" {
				action.Disabled = true
				action.DisabledReason = &reason
			}
		}
		result = append(result, action)
	}
	return result, nil
}

// ProjectName is the resolver for the projectName field.
func (r *queryResolver) ProjectName(ctx context.Context) (string, error) {
	return r.CoreResolver.ProjectName(ctx)
}

// MainBranch is the resolver for the mainBranch field.
func (r *queryResolver) MainBranch(ctx context.Context) (string, error) {
	return r.CoreResolver.MainBranch(ctx, r.ProjectRoot)
}

// AgentEnabled is the resolver for the agentEnabled field.
func (r *queryResolver) AgentEnabled(ctx context.Context) (bool, error) {
	cfg := r.Core.Config()
	if cfg == nil {
		return true, nil
	}
	return cfg.IsAgentEnabled(), nil
}

// WorktreeBaseRef is the resolver for the worktreeBaseRef field.
func (r *queryResolver) WorktreeBaseRef(ctx context.Context) (string, error) {
	cfg := r.Core.Config()
	if cfg == nil {
		return config.DefaultWorktreeBaseRef, nil
	}
	return cfg.GetWorktreeBaseRef(), nil
}

// WorktreeRunCommand is the resolver for the worktreeRunCommand field.
func (r *queryResolver) WorktreeRunCommand(ctx context.Context) (string, error) {
	cfg := r.Core.Config()
	if cfg == nil {
		return "", nil
	}
	return cfg.GetWorktreeRun(), nil
}

// WorkspacePort is the resolver for the workspacePort field.
func (r *queryResolver) WorkspacePort(ctx context.Context, workspaceID string) (int, error) {
	if r.PortAlloc == nil {
		return 0, nil
	}
	port, err := r.PortAlloc.Get(workspaceID)
	if err != nil {
		return 0, nil
	}
	return port, nil
}

// IsRunning is the resolver for the isRunning field.
func (r *queryResolver) IsRunning(ctx context.Context, workspaceID string) (bool, error) {
	if r.TerminalMgr == nil {
		return false, nil
	}
	sessionID := workspaceID + RunSessionSuffix
	sess := r.TerminalMgr.Get(sessionID)
	if sess == nil {
		return false, nil
	}
	return sess.Alive(), nil
}

// WorktreeIntegrateMode is the resolver for the worktreeIntegrateMode field.
func (r *queryResolver) WorktreeIntegrateMode(ctx context.Context) (string, error) {
	cfg := r.Core.Config()
	if cfg == nil {
		return string(config.IntegrateModeLocal), nil
	}
	return string(cfg.GetWorktreeIntegrate()), nil
}

// ListFiles is the resolver for the listFiles field.
// It does case-insensitive substring matching across all git-tracked file paths.
// Each query term (space-separated) must match somewhere in the path.
func (r *queryResolver) ListFiles(ctx context.Context, workspaceID *string, prefix string, limit *int) ([]*model.FileEntry, error) {
	dir := r.ProjectRoot
	if workspaceID != nil && *workspaceID != CentralSessionID {
		path, err := r.findWorktreePath(*workspaceID)
		if err != nil {
			return nil, err
		}
		dir = path
	}

	maxResults := 0 // 0 = no limit
	if limit != nil && *limit > 0 {
		maxResults = *limit
	}

	cmd := exec.CommandContext(ctx, "git", "ls-files")
	cmd.Dir = dir
	output, err := cmd.Output()
	if err != nil {
		return nil, fmt.Errorf("git ls-files: %w", err)
	}

	query := strings.ToLower(strings.TrimSpace(prefix))
	terms := strings.Fields(query)

	var results []*model.FileEntry

	for _, line := range strings.Split(strings.TrimSpace(string(output)), "\n") {
		if line == "" {
			continue
		}

		// All terms must match (case-insensitive) somewhere in the path
		lower := strings.ToLower(line)
		match := true
		for _, term := range terms {
			if !strings.Contains(lower, term) {
				match = false
				break
			}
		}
		if !match {
			continue
		}

		results = append(results, &model.FileEntry{Path: line})

		if maxResults > 0 && len(results) >= maxResults {
			break
		}
	}

	return results, nil
}

// BeanChanged is the resolver for the beanChanged field.
func (r *subscriptionResolver) BeanChanged(ctx context.Context, includeInitial *bool) (<-chan *model.BeanChangeEvent, error) {
	// Subscribe to bean events from beancore
	eventCh, unsubscribe := r.Core.Subscribe()

	// Create buffered output channel for GraphQL to reduce backpressure on the
	// subscriber channel. Without buffering, the resolver blocks on sends to gqlgen's
	// WebSocket transport, which prevents draining eventCh and causes fanOut to drop events.
	out := make(chan *model.BeanChangeEvent, 64)

	// Start goroutine to forward events
	go func() {
		defer unsubscribe()
		defer close(out)

		// sendSnapshot emits the full current state as one event. It is both the
		// initial payload and the answer to a resync: after beancore dropped
		// events for this subscriber, incremental updates would build on an
		// incomplete history, so the client replaces its state wholesale.
		sendSnapshot := func() bool {
			beans := r.Core.All()
			cfg := r.Core.Config()
			bean.SortByStatusPriorityAndType(beans, cfg.StatusNames(), cfg.PriorityNames(), cfg.TypeNames())

			select {
			case out <- &model.BeanChangeEvent{
				Type:  model.ChangeTypeInitialSnapshot,
				Beans: beans,
			}:
				return true
			case <-ctx.Done():
				return false
			}
		}

		// If includeInitial is true, emit all current beans as a single snapshot
		if includeInitial != nil && *includeInitial {
			if !sendSnapshot() {
				return
			}
		}

		for {
			select {
			case <-ctx.Done():
				// Client disconnected
				return
			case events, ok := <-eventCh:
				if !ok {
					// Channel closed (watcher stopped)
					return
				}

				// Forward each event to the GraphQL subscription
				for _, event := range events {
					if event.Type == beancore.EventResync {
						if !sendSnapshot() {
							return
						}
						continue
					}

					gqlEvent := &model.BeanChangeEvent{
						BeanID: event.BeanID,
						Bean:   event.Bean,
					}

					// Convert event type
					switch event.Type {
					case beancore.EventCreated:
						gqlEvent.Type = model.ChangeTypeCreated
					case beancore.EventUpdated:
						gqlEvent.Type = model.ChangeTypeUpdated
					case beancore.EventDeleted:
						gqlEvent.Type = model.ChangeTypeDeleted
					}

					select {
					case out <- gqlEvent:
						// Sent successfully
					case <-ctx.Done():
						return
					}
				}
			}
		}
	}()

	return out, nil
}

// WorktreesChanged is the resolver for the worktreesChanged field.
func (r *subscriptionResolver) WorktreesChanged(ctx context.Context) (<-chan []*model.Worktree, error) {
	if r.WorktreeMgr == nil {
		out := make(chan []*model.Worktree)
		close(out)
		return out, nil
	}

	ch := r.WorktreeMgr.Subscribe()
	out := make(chan []*model.Worktree)

	// buildWorktreeList converts worktree structs to GraphQL models without PR data.
	buildWorktreeList := func(wts []worktree.Worktree) []*model.Worktree {
		result := make([]*model.Worktree, len(wts))
		for i, wt := range wts {
			result[i] = worktreeToModel(&wt, r.Core, r.WorktreeMgr.BaseRef(), false)
		}
		return result
	}

	// wg tracks in-flight populatePRsAsync goroutines so we can wait for them
	// to finish before closing the out channel, preventing send-on-closed-channel panics.
	var wg sync.WaitGroup

	// populatePRsAsync fetches PR data for all worktrees in a single batch query,
	// then re-emits the updated list on the output channel.
	populatePRsAsync := func(result []*model.Worktree) {
		defer wg.Done()
		if r.Forge == nil || len(result) == 0 {
			return
		}
		populatePRsBatch(ctx, result, r.Forge, r.ProjectRoot)
		select {
		case out <- result:
		case <-ctx.Done():
		}
	}

	go func() {
		defer r.WorktreeMgr.Unsubscribe(ch)
		defer close(out)
		defer wg.Wait()

		// Emit the current list immediately without PR data, then
		// fetch PR data in the background and re-emit.
		if wts, err := r.WorktreeMgr.List(); err == nil {
			result := buildWorktreeList(wts)
			select {
			case out <- result:
			case <-ctx.Done():
				return
			}
			wg.Add(1)
			go populatePRsAsync(result)
		}

		// Periodically re-fetch PR data so sidebar icons stay current
		// even when no worktree filesystem events occur.
		prTicker := time.NewTicker(30 * time.Second)
		defer prTicker.Stop()

		// refreshPRs fetches the current worktree list with PR data and emits it.
		refreshPRs := func() {
			wts, err := r.WorktreeMgr.List()
			if err != nil {
				return
			}
			result := buildWorktreeList(wts)
			wg.Add(1)
			go populatePRsAsync(result)
		}

		for {
			select {
			case <-ctx.Done():
				return
			case _, ok := <-ch:
				if !ok {
					return
				}
				wts, err := r.WorktreeMgr.List()
				if err != nil {
					continue
				}
				result := buildWorktreeList(wts)
				select {
				case out <- result:
				case <-ctx.Done():
					return
				}
				wg.Add(1)
				go populatePRsAsync(result)
			case <-prTicker.C:
				refreshPRs()
			}
		}
	}()

	return out, nil
}

// AgentSessionChanged is the resolver for the agentSessionChanged field.
func (r *subscriptionResolver) AgentSessionChanged(ctx context.Context, beanID string) (<-chan *model.AgentSession, error) {
	if r.AgentMgr == nil {
		out := make(chan *model.AgentSession)
		close(out)
		return out, nil
	}

	ch := r.AgentMgr.Subscribe(beanID)
	out := make(chan *model.AgentSession)

	go func() {
		defer r.AgentMgr.Unsubscribe(beanID, ch)
		defer close(out)

		fetchState := func() *model.AgentSession {
			if s := r.AgentMgr.GetSession(beanID); s != nil {
				return agentSessionToModel(s)
			}
			// Session was cleared — send an empty session so the UI resets
			return &model.AgentSession{
				BeanID:    beanID,
				AgentType: "claude",
				Status:    model.AgentSessionStatusIdle,
				Messages:  []*model.AgentMessage{},
			}
		}

		// Emit current state immediately (if session exists)
		if s := r.AgentMgr.GetSession(beanID); s != nil {
			select {
			case out <- agentSessionToModel(s):
			case <-ctx.Done():
				return
			}
		}

		// Use a latest-value pattern: if new notifications arrive while
		// we're blocked sending to out, refresh the pending state so the
		// frontend always receives the most recent session state. This
		// prevents missed status transitions (e.g. IDLE→RUNNING) when
		// the WebSocket transport is slow to consume.
		var pending *model.AgentSession
		for {
			if pending == nil {
				// Wait for a notification
				select {
				case <-ctx.Done():
					return
				case _, ok := <-ch:
					if !ok {
						return
					}
					pending = fetchState()
				}
			} else {
				// Try to send, but refresh if a new notification arrives
				select {
				case out <- pending:
					pending = nil
				case _, ok := <-ch:
					if !ok {
						return
					}
					pending = fetchState()
				case <-ctx.Done():
					return
				}
			}
		}
	}()

	return out, nil
}

// ActiveAgentStatuses is the resolver for the activeAgentStatuses field.
func (r *subscriptionResolver) ActiveAgentStatuses(ctx context.Context) (<-chan []*model.ActiveAgentStatus, error) {
	if r.AgentMgr == nil {
		out := make(chan []*model.ActiveAgentStatus)
		close(out)
		return out, nil
	}

	ch := r.AgentMgr.SubscribeGlobal()
	out := make(chan []*model.ActiveAgentStatus)

	go func() {
		defer r.AgentMgr.UnsubscribeGlobal(ch)
		defer close(out)

		// Emit current state immediately
		select {
		case out <- activeAgentsToModel(r.AgentMgr.ListRunningSessions()):
		case <-ctx.Done():
			return
		}

		// Latest-value pattern (same as AgentSessionChanged above):
		// refresh pending state when new notifications arrive during
		// a blocked send.
		var pending []*model.ActiveAgentStatus
		for {
			if pending == nil {
				select {
				case <-ctx.Done():
					return
				case _, ok := <-ch:
					if !ok {
						return
					}
					pending = activeAgentsToModel(r.AgentMgr.ListRunningSessions())
				}
			} else {
				select {
				case out <- pending:
					pending = nil
				case _, ok := <-ch:
					if !ok {
						return
					}
					pending = activeAgentsToModel(r.AgentMgr.ListRunningSessions())
				case <-ctx.Done():
					return
				}
			}
		}
	}()

	return out, nil
}

// WorkspaceStatuses is the resolver for the workspaceStatuses field.
func (r *subscriptionResolver) WorkspaceStatuses(ctx context.Context) (<-chan []*model.WorkspaceStatus, error) {
	out := make(chan []*model.WorkspaceStatus)

	go func() {
		defer close(out)

		var wtCh chan struct{}
		if r.WorktreeMgr != nil {
			wtCh = r.WorktreeMgr.Subscribe()
			defer r.WorktreeMgr.Unsubscribe(wtCh)
		}

		ticker := time.NewTicker(10 * time.Second)
		defer ticker.Stop()

		// Track last emitted state to avoid sending duplicates.
		type statusKey struct{ hasChanges, hasUnmergedCommits bool }
		var lastStatuses map[string]statusKey

		compute := func() []*model.WorkspaceStatus {
			var result []*model.WorkspaceStatus

			// Main workspace status
			result = append(result, &model.WorkspaceStatus{
				ID:         CentralSessionID,
				HasChanges: gitutil.HasChanges(r.ProjectRoot),
			})

			// Worktree statuses
			if r.WorktreeMgr != nil {
				baseRef := r.WorktreeMgr.BaseRef()
				if wts, err := r.WorktreeMgr.List(); err == nil {
					for _, wt := range wts {
						result = append(result, &model.WorkspaceStatus{
							ID:                 wt.ID,
							HasChanges:         gitutil.HasChanges(wt.Path),
							HasUnmergedCommits: gitutil.HasUnmergedCommits(wt.Path, baseRef),
						})
					}
				}
			}

			return result
		}

		changed := func(statuses []*model.WorkspaceStatus) bool {
			if len(statuses) != len(lastStatuses) {
				return true
			}
			for _, s := range statuses {
				prev, ok := lastStatuses[s.ID]
				if !ok || prev.hasChanges != s.HasChanges || prev.hasUnmergedCommits != s.HasUnmergedCommits {
					return true
				}
			}
			return false
		}

		emit := func() {
			statuses := compute()
			if !changed(statuses) {
				return
			}
			lastStatuses = make(map[string]statusKey, len(statuses))
			for _, s := range statuses {
				lastStatuses[s.ID] = statusKey{s.HasChanges, s.HasUnmergedCommits}
			}
			select {
			case out <- statuses:
			case <-ctx.Done():
			}
		}

		emit() // initial state

		for {
			select {
			case <-ctx.Done():
				return
			case <-ticker.C:
				emit()
			case _, ok := <-wtCh:
				if !ok {
					return
				}
				emit()
			}
		}
	}()

	return out, nil
}

// Bean returns BeanResolver implementation.
func (r *Resolver) Bean() BeanResolver { return &beanResolver{r} }

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Subscription returns SubscriptionResolver implementation.
func (r *Resolver) Subscription() SubscriptionResolver { return &subscriptionResolver{r} }

type beanResolver struct{ *Resolver }
type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type subscriptionResolver struct{ *Resolver }
